[package]
name = "registers"
version = "0.1.0"
authors = ["Dan Pittman <dan@auxon.io>"]
edition = "2018"

[dependencies]
typenum = "1.10"
type_bounds = {git = "ssh://github.com/auxoncorp/type-bounds"}
