[package]
name = "registers"
version = "0.1.0"
authors = ["Dan Pittman <dan@auxon.io>"]
edition = "2018"

[dependencies]
typenum = {git = "git://github.com/pittma/typenum", branch = "not"}
type_bounds = {git = "git://github.com/auxoncorp/type-bounds", branch = "static" }
